# Generated by Django 3.2.6 on 2021-09-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20210912_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='123456', max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(default='123456', max_length=200),
        ),
    ]
