# Generated by Django 3.2.6 on 2021-09-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_mdicine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mdicine',
        ),
        migrations.AddField(
            model_name='medicine',
            name='remark',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
