# Generated by Django 3.2.6 on 2021-09-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20210913_2135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mdicine',
        ),
    ]
