# Generated by Django 3.2.6 on 2021-09-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_medicine_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='specification',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
