# Generated by Django 3.2.6 on 2021-09-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_medicine_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='productiondate',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='medicine',
            name='shelflife',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
