# Generated by Django 3.2.6 on 2021-09-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20210913_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicinemanager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
