# Generated by Django 3.2.6 on 2021-09-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_doctor_iswork'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='now_queue',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='queue',
            field=models.BigIntegerField(default=0),
        ),
    ]
