# Generated by Django 3.2.6 on 2021-09-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_auto_20210914_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='doctor_id',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='medicinelist_id',
            field=models.BigIntegerField(blank=True),
        ),
    ]
