# Generated by Django 3.2.6 on 2021-09-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_auto_20210914_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200)),
                ('now_queue', models.BigIntegerField()),
                ('queue', models.BigIntegerField()),
            ],
        ),
    ]
