# Generated by Django 3.2.6 on 2021-09-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_rename_department_queue_depart'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinelist',
            name='medicinlist_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
