# Generated by Django 3.2.6 on 2021-09-16 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_medicinelist_medicinlist_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicinelist',
            old_name='medicinlist_id',
            new_name='medicinelist_id',
        ),
    ]
