# Generated by Django 3.2.6 on 2021-09-17 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_rename_medicinlist_id_medicinelist_medicinelist_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='queue',
            new_name='patientqueue',
        ),
    ]
