# Generated by Django 3.2.6 on 2021-09-17 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_rename_queue_medicalrecord_patientqueue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='now_queue',
        ),
    ]
